# Generated by Django 4.0.8 on 2023-01-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYENNE', 'Moyenne'), ('ELEVEE', 'Elevée')], max_length=30, verbose_name='Priorité'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('AFAIRE', 'A faire'), ('ENCOURS', 'En cours'), ('TERMINE', 'Terminé')], max_length=30),
        ),
    ]
