# Generated by Django 4.0.8 on 2023-01-13 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_issue_priority_alter_issue_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='assignee_user',
            new_name='assignee',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='author_user',
            new_name='author',
        ),
    ]
